name: Linting

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          src: "./"

      - name: Run Ruff formatter check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./"
          args: "format --check"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Run ty type checker (experimental - allowed to fail)
        run: uv run ty check *.py || echo "ty type checker failed (expected in pre-alpha)"
        continue-on-error: true
